# Generated by Django 4.1 on 2023-07-20 04:22

from django.db import migrations, models
import django.db.models.deletion
import pedidos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabeceraPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('cliente', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[(pedidos.models.EstadoPedido['EN_PROCESO'], 'EN_PROCESO'), (pedidos.models.EstadoPedido['ENVIADO'], 'ENVIADO'), (pedidos.models.EstadoPedido['CONFIRMADO'], 'CONFIRMADO'), (pedidos.models.EstadoPedido['CONFIRMADO'], 'COMPLETADO')], default=pedidos.models.EstadoPedido['EN_PROCESO'], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cabecera_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.cabecerapedido')),
            ],
        ),
    ]
