# Generated by Django 4.1 on 2023-07-23 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pedidos.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='cabecerapedido',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='stock_operacional',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='sugerido',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='vencido',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cabecerapedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cabecerapedido',
            name='estado',
            field=models.CharField(choices=[(pedidos.models.EstadoPedido['EN_PROCESO'], 'EN_PROCESO'), (pedidos.models.EstadoPedido['ENVIADO'], 'ENVIADO'), (pedidos.models.EstadoPedido['CONFIRMADO'], 'CONFIRMADO'), (pedidos.models.EstadoPedido['COMPLETADO'], 'COMPLETADO')], default=pedidos.models.EstadoPedido['EN_PROCESO'], max_length=20),
        ),
    ]
