# Generated by Django 4.1 on 2023-07-23 20:52

from django.db import migrations, models
import pedidos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_detallepedido_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecerapedido',
            name='estado',
            field=models.CharField(choices=[(pedidos.models.EstadoPedido['EN_PROCESO'], 'EN_PROCESO'), (pedidos.models.EstadoPedido['ENVIADO'], 'ENVIADO'), (pedidos.models.EstadoPedido['CONFIRMADO'], 'CONFIRMADO'), (pedidos.models.EstadoPedido['COMPLETADO'], 'COMPLETADO')], default=pedidos.models.EstadoPedido['EN_PROCESO'], max_length=100),
        ),
    ]
