# Generated by Django 4.1 on 2023-07-23 23:53

from django.db import migrations, models
import pedidos.models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_cabecerapedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecerapedido',
            name='estado',
            field=models.CharField(choices=[('EN_PROCESO', pedidos.models.EstadoPedido['EN_PROCESO']), ('ENVIADO', pedidos.models.EstadoPedido['ENVIADO']), ('CONFIRMADO', pedidos.models.EstadoPedido['CONFIRMADO']), ('COMPLETADO', pedidos.models.EstadoPedido['COMPLETADO'])], default=pedidos.models.EstadoPedido['EN_PROCESO'], max_length=100),
        ),
    ]
